# Form implementation generated from reading ui file 'fixturepatch.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(461, 389)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.label_29 = QtWidgets.QLabel(parent=self.wizardPage1)
        self.label_29.setGeometry(QtCore.QRect(0, 0, 378, 31))
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(parent=self.wizardPage1)
        self.label_32.setGeometry(QtCore.QRect(0, 30, 461, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.wizardPage1)
        self.label_33.setGeometry(QtCore.QRect(0, 190, 371, 51))
        self.label_33.setObjectName("label_33")
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.label_30 = QtWidgets.QLabel(parent=self.wizardPage2)
        self.label_30.setGeometry(QtCore.QRect(0, 0, 378, 31))
        self.label_30.setObjectName("label_30")
        self.label = QtWidgets.QLabel(parent=self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(0, 25, 441, 31))
        self.label.setObjectName("label")
        self.label_34 = QtWidgets.QLabel(parent=self.wizardPage2)
        self.label_34.setGeometry(QtCore.QRect(0, 280, 371, 51))
        self.label_34.setObjectName("label_34")
        self.fixtureprofiletreeview = QtWidgets.QTreeView(parent=self.wizardPage2)
        self.fixtureprofiletreeview.setGeometry(QtCore.QRect(0, 60, 256, 192))
        self.fixtureprofiletreeview.setObjectName("fixtureprofiletreeview")
        self.label_2 = QtWidgets.QLabel(parent=self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(270, 60, 181, 31))
        self.label_2.setObjectName("label_2")
        self.startingchannels = QtWidgets.QLineEdit(parent=self.wizardPage2)
        self.startingchannels.setGeometry(QtCore.QRect(270, 100, 113, 22))
        self.startingchannels.setCursorPosition(0)
        self.startingchannels.setObjectName("startingchannels")
        self.widget = QtWidgets.QWidget(parent=self.wizardPage2)
        self.widget.setGeometry(QtCore.QRect(270, 150, 173, 54))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=self.widget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 1, 2, 1, 1)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.label_31 = QtWidgets.QLabel(parent=self.wizardPage)
        self.label_31.setGeometry(QtCore.QRect(0, 0, 378, 31))
        self.label_31.setObjectName("label_31")
        self.label_60 = QtWidgets.QLabel(parent=self.wizardPage)
        self.label_60.setGeometry(QtCore.QRect(0, 20, 371, 31))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(parent=self.wizardPage)
        self.label_61.setGeometry(QtCore.QRect(0, 300, 371, 31))
        self.label_61.setObjectName("label_61")
        Wizard.addPage(self.wizardPage)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.label_29.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">FIXTURE PATCH WIZARD</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_32.setText(_translate("Wizard", "This configurator deals with the patching of the fixture \n"
"profiles we created in the last section"))
        self.label_33.setText(_translate("Wizard", "Press <NEXT> to continue with the configuration\n"
"Press <CANCEL> to exit the configurator"))
        self.label_30.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">FIXTURE PATCH WIZARD</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label.setText(_translate("Wizard", "Select a fixture and then enter the start channel for each fixture you \n"
"would like to patch seperated by a comma."))
        self.label_34.setText(_translate("Wizard", "Press <NEXT> to continue with the configuration\n"
"Press <CANCEL> to exit the configurator"))
        self.label_2.setText(_translate("Wizard", "Starting channels: \n"
"(Seperate with comma)"))
        self.label_3.setText(_translate("Wizard", "Channels In Use:"))
        self.label_4.setText(_translate("Wizard", "Channels Free:"))
        self.label_31.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">FIXTURE PATCH WIZARD</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_60.setText(_translate("Wizard", "The fixture patch wizard has finished."))
        self.label_61.setText(_translate("Wizard", "Press <FINISH> to save and return to the main configurator\n"
"Press <CANCEL> to quit the configurator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wizard = QtWidgets.QWizard()
    ui = Ui_Wizard()
    ui.setupUi(Wizard)
    Wizard.show()
    sys.exit(app.exec())
